on:
  pull_request:
    types: [ opened ]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Pull Request Validation
      uses: Ash258/Scoop-GithubActions@stable
      env:
        GITH_EMAIL: 49682577+yuuki76@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
